<?php
$e = static fn($value): string => htmlspecialchars((string) ($value ?? ''), ENT_QUOTES, 'UTF-8');
$columns = $data === [] ? [] : array_keys($data[0]);
$appName = $settings['app.name'] ?? ($_ENV['APP_NAME'] ?? 'IT Inventory');
?>
<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:28px 30px 42px}body{font-family:DejaVu Sans,sans-serif;color:#17211f;font-size:9px}h1{font-size:20px;margin:0 0 5px;color:#0f766e}.meta{color:#63706d;margin-bottom:20px}.brand{font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#0f766e;margin-bottom:14px}table{border-collapse:collapse;width:100%;table-layout:auto}th{background:#e8f3f0;text-align:left;color:#145f55}th,td{border:1px solid #d8e1df;padding:6px;vertical-align:top;overflow-wrap:anywhere}tr:nth-child(even) td{background:#f8faf9}.footer{position:fixed;bottom:-26px;left:0;right:0;border-top:1px solid #d8e1df;padding-top:7px;color:#66736f;font-size:8px}
</style></head><body><div class="brand"><?= $e($appName) ?></div><h1><?= $e($title) ?></h1><div class="meta">Generated <?= $e(date('M j, Y g:i A')) ?> by <?= $e($_SESSION['name'] ?? 'System') ?></div>
<table><thead><tr><?php foreach ($columns as $column): ?><th><?= $e(ucwords(str_replace('_', ' ', $column))) ?></th><?php endforeach; ?></tr></thead><tbody>
<?php if ($data === []): ?><tr><td>No records found.</td></tr><?php else: foreach ($data as $row): ?><tr><?php foreach ($columns as $column): ?><td><?= $e($row[$column]) ?></td><?php endforeach; ?></tr><?php endforeach; endif; ?>
</tbody></table><div class="footer"><?= $e($settings['reports.footer'] ?? 'Generated by IT Inventory') ?></div></body></html>
